backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  identity_url: "https://hardcore-panini-a59101.netlify.com/.netlify/identity"
  gateway_url: "https://hardcore-panini-a59101.netlify.com/.netlify/git"

publish_mode: editorial_workflow
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - label: "Global"
    name: "global"
    files:
      - label: "Stuff"
        name: "stuff"
        file: "_data/stuff.yml"
        fields:
          - {label: First Name, name: first, widget: string}
          - {label: Last Name, name: last, widget: string}
          - {label: Logo, name: logo, widget: image, hint: "Displays in the header"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Letter, name: letter, widget: markdown}
      - label: "FAQ Page"
        name: "faq"
        file: "_data/faq.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - label: FAQs
            name: faqs
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: text}
